# all data here will crate awarness of all nuke related apps as:
# [nuke, nukex, nuke-studio, nuke-assist, hiero, hiero-player]
#

# set verson we are looking for in default nuke installation dir
version = "11.1v4"

[platform]
windows = 'C:\\Program Files\Nuke'
linux = '/usr/local/Nuke'
darvin = '/Applications/Nuke'

[required.avalon] # path to `avalon_nuke` needed for running nuke avalon
path = "{app.sys.avalon.path}" # path to `avalon_nuke` needed for running nuke avalon

[required.pyblish] # path to `pyblish_nuke` needed for running nuke pyblish
path = "{app.sys.pyblish.path}"
ui = "qml"

[required.qt] # path to `qt` compatible to nuke qt needed for running nuke pyblish
path = "{root}/app/vendor/python-qt5/python_qt5"

[required.qml] # path to `qml` compatible to nuke qt needed for running nuke pyblish_nukeqml
path = "{root}/app/vendor/pyblish-qml/pyblish_qml"

[required.tools.scripts] # path to company custom scripts
path = ""

[required.tools.gizmos] # path to company custom gizmo
path = ""

# registering app shortcut for the `louncher`
[apps.nuke]
suffix = ""
path = "{app-store.bin.nuke.platform}{app-store.bin.nuke.version}"
cmd = "{app-store.bin.nuke.apps.nuke.path} {app-store.bin.nuke.apps.nuke.suffix}"
"python.path" = "" # path to modules needed for running nuke wrapper

# registering app shortcut for the `louncher`
[apps.nuke-studio]
suffix = "--nukestudio"
path = "{app-store.bin.nuke.platform}{app-store.bin.nuke.version}"
cmd = "{app-store.bin.nuke.apps.nuke-studio.path} {app-store.bin.nuke.apps.nuke-studio.suffix}"
"python.path" = "" # path to modules needed for running nuke wrapper

# registering app shortcut for the `louncher`
[apps.nuke-assist]
suffix = "--assist"
path = "{app-store.bin.nuke.platform}{app-store.bin.nuke.version}"
cmd = "{app-store.bin.nuke.apps.nuke-assist.path} {app-store.bin.nuke.apps.nuke-assist.suffix}"
"python.path" = "" # path to modules needed for running nuke wrapper

# registering app shortcut for the `louncher`
[apps.nuke-x]
suffix = "--nukex"
path = "{app-store.bin.nuke.platform}{app-store.bin.nuke.version}"
cmd = "{app-store.bin.nuke.apps.nuke-x.path} {app-store.bin.nuke.apps.nuke-x.suffix}"
"python.path" = "" # path to modules needed for running nuke wrapper


[apps.hiero]
suffix = "--hiero"
path = "{app-store.bin.nuke.platform}{app-store.bin.nuke.version}"
cmd = "{app-store.bin.nuke.apps.hiero.path} {app-store.bin.nuke.apps.hiero.suffix}"
"python.path" = "" # path to modules needed for running nuke wrapper


[apps.hiero-player]
suffix = "--hieroplayer"
path = "{app-store.bin.nuke.platform}{app-store.bin.nuke.version}"
cmd = "{app-store.bin.nuke.apps.hiero-player.path} {app-store.bin.nuke.apps.hiero-player.suffix}"
"python.path" = "" # path to modules needed for running nuke wrapper
