channels:
  - conda-forge

dependencies:
  - mongodb=3.4.10
  - python=2.7
  - git=2.14.1
  - pyside2
  - pip:
    - pymongo==3.6.1
    - checksumdir
    - toml
    - autopep8
    - pep8
    - jedi
    - flake8
    - psutil
    - gitpython
    - colorama
    - Xlib
