
# toml .configuration file generated automatically if not present
# please adjust this file as `your preset`

[sys.python.dev]
    version = "3.6.6"
    path = "__DEV__/{sys.python.dev.version}/dist/{platform}/bin"
    mode = false # all small caps > if true then executable run from __DEV__

[sys.python]
    path = "{root}/python[/{sys.python.dev.path}]"

##############################################################################
[avalon]
    git = "git@github.com:pypeclub/avalon-core.git|master" # brach is optional
    path = "{app_store.path}/avalon-core"
    qt = "{root}/python[/__DEV__]/Qt5"
    # demonstration purouse only > this will come later from the tool itself
    menu = ['Config core','Create new project','______','Save database',]

[avalon.launcher]
    git = "git@github.com:pypeclub/avalon-launcher.git|master" # brach is optional
    path = "{app_store.path}/avalon-launcher"
    qt = "{root}/python[/__DEV__]/Qt5"

[pyblish]
    git = "git@github.com:pypeclub/pyblish-base.git|master" # brach is optional
    path = "{app_store.path}/pyblish-base"
    qt = "{root}/python[/__DEV__]/Qt5"
    # microplugin manager: spin of [w_hotbox](http://www.nukepedia.com/python/ui/w_hotbox)
    menu = ['Config Pyblish', 'Create new micro-plugin', '______', 'Micro-plugins manager',]

[pyblish.qml]
    git = "git@github.com:pypeclub/pyblish-qml.git|master" # brach is optional
    path = "{app_store.path}/pyblish-qml"
    qt = "{root}/python[/__DEV__]/Qt5"
