# core repos
[AVALON_CORE]
    name = "avalon-core"
    subdir = "avalon"
    git = "git@github.com:pypeclub/avalon-core.git"
    branch = "pypeclub-nuke-workflow-jezschaj"
    submodule_root = "app/repos"
    env = "pythonpath"

[AVALON_LAUNCHER]
    name = "avalon-launcher"
    subdir = "launcher"
    git = "https://github.com/getavalon/launcher.git"
    branch = "master"
    submodule_root = "app/repos"
    env = "pythonpath"

[PYBLISH_BASE]
    name = "pyblish-base"
    subdir = "pyblish"
    git = "https://github.com/pyblish/pyblish-base.git"
    branch = "master"
    submodule_root = "app/repos"
    env = "pythonpath"

[PYBLISH_QML]
    name = "pyblish-qml"
    subdir = "pyblish_qml"
    git = "https://github.com/pyblish/pyblish-qml.git"
    branch = "master"
    submodule_root = "app/repos"
    env = "pythonpath"

[PYBLISH_LITE]
    name = "pyblish-lite"
    subdir = "pyblish_lite"
    git = "https://github.com/pyblish/pyblish-lite.git"
    branch = "master"
    submodule_root = "app/repos"
    env = "pythonpath"

[AVALON_EXAMPLES]
    name = "avalon-examples"
    subdir = "projects"
    git = "https://github.com/getavalon/examples.git"
    branch = "master"
    submodule_root = "app/repos"
    env = "pythonpath"

# studio repos
[PYPE_STUDIO_CONFIG]
    name = "studio-config"
    subdir = "pype"
    git = "git@github.com:pypeclub/studio-config.git"
    branch = "master"
    submodule_root = "studio"
    env = "pythonpath"

[PYPE_STUDIO_TEMPLATES]
    name = "studio-templates"
    subdir = "templates"
    git = "git@github.com:pypeclub/studio-templates.git"
    branch = "master"
    submodule_root = "studio"
    env = "path"

[PYPE_STUDIO_PROJECTS]
    name = "studio-projects"
    subdir = "projects"
    git = "git@github.com:pypeclub/studio-projects.git"
    branch = "master"
    submodule_root = "studio"
    env = "path"
